version: "2"

services:
  reverseproxy:
    container_name: reverseproxy
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "81:443"
      - "443:443"

  laravel-task:
    container_name: laravel-task
    image: webdevops/php-apache:7.4
    volumes:
        - ./src/laravel:/app
    environment:
        - WEB_DOCUMENT_ROOT=/app/public
        - VIRTUAL_HOST=laravel-task.local
    hostname: shopping-store.local
    domainname: shopping-store.local

  rabbitmq1:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - ./enabled_plugins:/var/lib/rabbitmq/enabled_plugins
    domainname: rabbitmq.local
